version: '2'

services:

  registry:
    container_name: registry
    build:
      context: .
    image: registry:2
    ports:
      - "5003:5000"
    networks:
      - infra-base

networks:
  infra-base:
    driver: bridge