apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PWD
          value: root_password
        - name: MYSQL_USER
          value: keystone
        - name: MYSQL_USER_PWD
          value: keystone_password
        - name: MYSQL_USER_DB
          value: keystone
        name: db
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-claim0
      restartPolicy: Always
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
status: {}
