apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: memcache
  name: memcache
spec:
  ports:
  - name: "11211"
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    service: memcache
status:
  loadBalancer: {}
