apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rabbit
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: rabbit
    spec:
      containers:
      - name: rabbit
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 5671
          protocol: TCP
        - containerPort: 4369
          protocol: TCP
        - containerPort: 25672
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /data/mnesia
          name: rabbit-claim0
      restartPolicy: Always
      volumes:
      - name: rabbit-claim0
        persistentVolumeClaim:
          claimName: rabbit-claim0
status: {}
