apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: rabbit
  name: rabbit
spec:
  ports:
  - name: "5672"
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: "5671"
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: "4369"
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: "25672"
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    service: rabbit
status:
  loadBalancer: {}
